In [3]:
import numpy as np
list = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(list)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
c = np.zeros(10, dtype = int)
c [4] = 1
c

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [9]:
a = np.linspace(9, 49)
a

array([ 9.        ,  9.81632653, 10.63265306, 11.44897959, 12.26530612,
       13.08163265, 13.89795918, 14.71428571, 15.53061224, 16.34693878,
       17.16326531, 17.97959184, 18.79591837, 19.6122449 , 20.42857143,
       21.24489796, 22.06122449, 22.87755102, 23.69387755, 24.51020408,
       25.32653061, 26.14285714, 26.95918367, 27.7755102 , 28.59183673,
       29.40816327, 30.2244898 , 31.04081633, 31.85714286, 32.67346939,
       33.48979592, 34.30612245, 35.12244898, 35.93877551, 36.75510204,
       37.57142857, 38.3877551 , 39.20408163, 40.02040816, 40.83673469,
       41.65306122, 42.46938776, 43.28571429, 44.10204082, 44.91836735,
       45.73469388, 46.55102041, 47.36734694, 48.18367347, 49.        ])

In [11]:
a = np.eye(5,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [2]:
import numpy as np
a = np.linspace(0, 5, 9)
b = np.around(a, 2)
b

array([0.  , 0.62, 1.25, 1.88, 2.5 , 3.12, 3.75, 4.38, 5.  ])

In [5]:
li = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
array = np.array(li)
print(array[2, :3])
print(array[1:4, 3])


[11 12 13]
[ 9 14 19]


In [9]:
np.logical_not(array)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [19]:
a = [1,2,3,4,5,6,7,8,9,10]
b = np.array(a)
new_arr = np.where((b%2)!= 0)
b[new_arr] = -1
b

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = np.where((arr >= 3) & (arr <= 8), -arr, arr)
print(arr)


[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [19]:
a = np.random.randint(1, 30, (4, 5))
print (a)

[[ 1 26 29 15  9]
 [23  6  7 12 14]
 [ 3 21 11 17  5]
 [25 24 12 27  2]]


In [21]:

sorted = a[a[:, 1].sort()]
print(sorted)


[[[ 1  6 29 15  9]
  [23 21  7 12 14]
  [ 3 24 11 17  5]
  [25 26 12 27  2]]]


In [24]:
import numpy as np
a = np.random.randint(1, 30, (4, 5))
sorted_a = a[a[:, 1].argsort()]

print("Original array:")
print(a)
print("\nSorted array based on the second column:")
print(sorted_a)


Original array:
[[ 6  4 22  4 22]
 [ 5 28 19 12 26]
 [20 10  2 13 17]
 [ 5 25 10 29 29]]

Sorted array based on the second column:
[[ 6  4 22  4 22]
 [20 10  2 13 17]
 [ 5 25 10 29 29]
 [ 5 28 19 12 26]]


In [26]:
b = np.resize(a ,(3,4))
b

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [31]:
import numpy as np
import csv

file_obj = open('terrorismData.csv', encoding='utf-8')
data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
country = []
for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_country = np.array(country)

np_killed[np_killed == ''] = '0.0'

np_killed = np.array(np_killed, dtype = float)

bool_arr = np_country == 'United States'
ans = np_killed[bool_arr]
print(ans)
print(sum(ans))

[0. 0. 0. ... 0. 0. 1.]
3771.0
