In [1]:
import numpy as np

In [4]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T   # T is for transpose
X.shape, Y.shape

((4, 2), (4, 1))

In [5]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [14]:
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [23]:
weights = 2 * np.random.random((2, 1)) - 1    # this 2 will increase our range 0 to 1 -> 0 to 2 and subtracting 1 from it will basically set our range between -1 to 1.
bias = 2 * np.random.random(1) - 1
weights, bias # and this (2, 1) is the shape we have given in the random function of random module
lr = 0.1

In [9]:
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.52735349],
       [0.41135524],
       [0.45267641],
       [0.34124485]])

In [10]:
# this was simple forward propagation without any hidden layers

In [11]:
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1

output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

# backward propagation

In [24]:
output0 = X
for iter in range(10000):
    output = sig(np.dot(output0, weights) + bias)
    
    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term + second_term
    first_two.shape
    
    changes = np.array([[0.0],[0.0]])
    
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]
    weights = weights - lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias = bias - lr * bias_change
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[8.6738676],
        [8.6738676]]),
 array([-14.84570058]),
 array([[3.56939002e-07],
        [2.08305814e-03],
        [2.08305814e-03],
        [9.24284332e-01]]))

In [25]:
output0 = X
for iter in range(10000):
    output = sig(np.dot(output0, weights) + bias)
    
    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term + second_term
    first_two.shape
    
    changes = np.dot(output0.T, first_two)
    weights = weights - lr*changes
    bias_change = bias - lr * bias_change
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[8.74183408],
        [8.74183408]]),
 array([-14.84570058]),
 array([[3.56939002e-07],
        [2.22923184e-03],
        [2.22923184e-03],
        [9.33265495e-01]]))