In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]]).T   # T is for transpose
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [7]:
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1
lr = 0.1

In [9]:
for iter in range(10000):
    output0 = X
    inputHidden = np.dot(output0, wh) + bh
    outputHidden = sig(np.dot(output0, wh) + bh)
    inputForOutputLayer = np.dot(outputHidden, wo) + bo
    output = sig(np.dot(outputHidden, wo) + bo)
    
    first_term_output_layer = output - Y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer*second_term_output_layer
    
    first_term_hidden_layer = np.dot(first_two_output_layer, wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer
    
    changes_output = np.dot(outputHidden.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis = 0, keepdims = True)
    
    changes_hidden = np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis = 0, keepdims = True)
    
    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias

    wh = wh - lr*changes_output
    bh = bh - lr*changes_hidden_bias

output0 = X
inputHidden = np.dot(output0, wh) + bh
outputHidden = sig(np.dot(output0, wh) + bh)
inputForOutputLayer = np.dot(outputHidden, wo) + bo
output = sig(np.dot(outputHidden, wo) + bo)
output, wh, bh, wo, bo

(array([[0.04133359],
        [0.95123896],
        [0.95999312],
        [0.03867017]]),
 array([[ 7.68301643,  8.22717026],
        [-7.11865269, -7.22546424]]),
 array([[-3.64583432,  3.00166591]]),
 array([[ 6.93584466],
        [-6.70523821]]),
 array([[3.06745443]]))